name: Deploy Hello World to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          # Set the necessary environment variables
          EC2_USER="ubuntu"
          EC2_IP="${{ secrets.EC2_PUBLIC_IP }}"
          
          # SSH into the EC2 instance and deploy the hello world page
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP << 'EOF'
            # Ensure nginx is installed and running
            sudo apt-get update
            sudo apt-get install -y nginx
            echo "Hello, World!" | sudo tee /var/www/html/index.html
            sudo systemctl restart nginx
          EOF
